export const PLAYING = 'PLAYER/PLAYING';
export const PLAY = 'PLAYER/PLAY';
export const PAUSE = 'PLAYER/PAUSE';
export const RENDER = 'PLAYER/RENDER';
export const ADD_PLAYER_EVENT = 'PLAYER/ADD_EVENT';
export const CHANGED_SETTINGS_VALUE = 'SETTINGS/CHANGED';
export const RESET_SETTINGS_VALUE = 'SETTINGS/RESET';
